sudo: required
services:
    - docker

before_install:
    - docker build -t kdmalviyan/docker-react-travis -f Dockerfile.dev .

script:
    - docker run -e CI=true kdmalviyan/docker-react-travis npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-travis"
    env: "DockerReactTravis-env"
    bucket_name: "elasticbeanstalk-us-east-2-836379380076"
    bucket_path: "docker-react-travis"
    on:
        branch: master
    access_key_id: "AKIA4FPAYRFWO56LP4XJ"
    secret_access_key: "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"